### ISSUE TITLE
login redirect should add a return url

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-frontend#139]
if I visit the frontend while not logged in, it correctly redirects me to /v1/auth, correctly setting the app_name parameter.

But it does not set the optional second parameter, dropoff_url, which means I always end up at the default dropoff location, which is also visited after logout, so this can't be the frontend app (or I'd go right back to logging in after logout).

It would be good if the dropoff_url parameter is set to a return URL (must be absolute URL).

**Comment by angryzor** [comment]
Yes, but there was a particular reason for this, related to local development and CORS. I'll check if that still causes issues, if so I'll try to make it add the dropoff_url when running non-locally.
