### ISSUE TITLE
We need to inform users that our system uses "just functional cookies".

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-frontend#150]
(currently clearing up what exactly we need, does it have to be a pop-up, etc...)

This issue is just a placeholder so we don't forget about this.

**Comment by Thiritin** [comment]
Functional cookies do not need consent. Source: https://gdpr.eu/cookies/

> Cookie compliance
> To comply with the regulations governing cookies under the GDPR and the ePrivacy Directive you must:

> Receive users’ consent before you use any cookies except strictly necessary cookies.
> Provide accurate and specific information about the data each cookie tracks and its purpose in plain language before consent is received.
> Document and store consent received from users.
> Allow users to access your service even if they refuse to allow the use of certain cookies
> Make it as easy for users to withdraw their consent as it was for them to give their consent in the first place.

**Comment by Jumpy-Squirrel** [comment]
Issue under discussion with our data protection officer :)

**Comment by Jumpy-Squirrel** [comment]
Text "We only use functional / essential cookies" and just an OK button is the decision.

**Comment by Jumpy-Squirrel** [comment]
... to be displayed in the IDP, not the regsys, because there cookies happen first, and we're the same convention.

Closing this here.
