### ISSUE TITLE
textual adaptations

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-frontend#165]
I need an issue so I can commit any textual changes that crop up during testing.

It's perfectly alright if I need to de-conflict, this is just so small stuff doesn't get forgotten

**Comment by angryzor** [comment]
Please also have a look at https://github.com/eurofurence/reg-frontend/commits/main/src/localizations/en.ftl

I have added some new localization message in the past few days that need a German translation.
