### ISSUE TITLE
regsys does not notice when email address was confirmed

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-frontend#168]
Right now, I need to log out and back in for system to realize my email has been confirmed - annoying for users and a bit hard to understand. Could be solved by a simple "retry" button on the "you must confirm your email" message page that sends user to authsrv again and thus refreshes the cookie with current information.

The underlying reason for this is that the high performance frontend-userinfo endpoint relies on the JWT in the cookie only, but this is not something we can change without losing the "high performance" property.

**Comment by angryzor** [comment]
Ah ok, I did not know this, thought a refresh would be sufficient. I'll add a button.
