### ISSUE TITLE
some information about what's wrong when submit fails, and cannot submit again after going back and fixing stuff

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-frontend#172]
I agree that with correct validations, usually it shouldn't happen that users end up on the "Oops we couldn't submit" page, but considering that normally users won't see it, it would probably be good to show the error details from ErrorDto to the user to give them some idea what went wrong.

And we absolutely must provide them with the requestid field from ErrorDto, or else they can't create a ticket to get help because we won't be able to find their request in the logs.

While testing, when I went back to change something after submit failed, I couldn't submit again until I reloaded the page.

**Comment by angryzor** [comment]
I reworked the errors last week and put the catchErrors at a wrong level, where they already crash the epic, hence events are no longer properly processed afterwards.
