### ISSUE TITLE
retain packages that are unknown to the frontend when editing existing registrations

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-frontend#201]
We always have a bunch of readonly packages (set by admins) such as
- Dealers' Den table fee
- Summerboat fee

While the frontend does not need to support them or explicitly display them, it is important that unknown packages are kept if a user changes their packages. Meaning, if you get an unknown package from the attendee-service, it should still be included when you update packages.

Otherwise the update will fail due to "unsupported addition or removal of read-only package xyz".

**Comment by angryzor** [comment]
If you say "the frontend doesn't need to support them" does that mean that these fees will be paid separately?

**Comment by Jumpy-Squirrel** [comment]
> If you say "the frontend doesn't need to support them" does that mean that these fees will be paid separately?

No, they'll be part of the dues balance, I just meant that there needs to be no way to select/deselect them, or individually see what they are.

The blue box should somehow show the amount, but it can be a total for "other" if need be. Those who have these packages will know that they're for the DD, Artshow, or Boat Trip, as they'll have signed up for them in a separate system.
