### ISSUE TITLE
UI issues during initial registration

### ISSUE THREAD

**Issue by Jumpy-Squirrel** [eurofurence/reg-frontend#91]
As I make my first new registration (which generally worked), I have noticed some issues. I am collecting them here and will continue to edit this issue, so we have a basis for discussion. These might well result in some separate issues.

- the registration form is available even before reg is opened. It is probably a good idea to query the countdown endpoint so we can have a time at which the form becomes available depending on the groups a user is in (earlier for early reg people, later for normal people).
- the registration form is available even while not logged in, this should immediately redirect to auth start. You cannot register or view registrations without being logged in.

- the state field is considered mandatory by the frontend, but it isn't
- individual field validation rules should immediately validate and indicate this to the user, maybe when leaving the field. The Continue button stays at the page, so it is validated, but the user gets no immediate feedback.

- the privacy policy, cookie statement, contact eurofurence links aren't links yet (legally required) -> Put in config in PR, so they can be displayed

- the t-shirt dropdown should get the descriptions for the choice values from the internationalization instead of directly listing their codes

- when submitting a new registration that contains validation errors, the error response does not reach the user. It just stays on the page
- Country should be a dropdown, with display values coming from i18n and codes coming from config.ts (the backend has a definitive list)

- The stage pass should be pre-selected by default (more generally, packages, flags and options need to have configuration for "selected by default"). This begins with the choice for day guest or normal guest, here normal guest should be pre-selected (can be hardcoded for now)

- right now, we are allowing multiple registrations per IDP account. This is fine, but then the user needs to have some way to say "I want to make a new reg" vs. "I want to edit my existing reg". Maybe this could be distinguished by route parameter, tbd -> Add to backend that new regs for existing subjects are rejected as duplicate 409, except for admins.

- the telegram field seems to be missing

**Comment by angryzor** [comment]
Would it be possible to split this up into multiple issues? It'll be easier to track and comment on these issues that way.

The following issue already has an associated ticket:
* the mouse cursor when hovering over "go back" does not change to the hand, so it's not clear this is clickable -> #79

**Comment by Jumpy-Squirrel** [comment]
> Would it be possible to split this up into multiple issues? It'll be easier to track and comment on these issues that way.
> 
> The following issue already has an associated ticket:
> 
>     * the mouse cursor when hovering over "go back" does not change to the hand, so it's not clear this is clickable -> [Back button doesn't seem to have pointer cursor #79](https://github.com/eurofurence/reg-frontend/issues/79)

Absolutely, I just wanted to have these in a list so we can go through them before I open individual tickets.

**Comment by Jumpy-Squirrel** [comment]
Transferred everything to individual issues. Closing.
