### ISSUE TITLE
On first load, query countdown endpoint to check if a reg exists and reg is open

### ISSUE THREAD

**Issue by angryzor** [eurofurence/reg-frontend#98]

**Comment by Jumpy-Squirrel** [comment]
Some more details, also see my draft PR for details about the API calls needed:

- the registration form is available even before reg is opened. It is probably a good idea to query the countdown endpoint so we can have a time at which the form becomes available depending on the groups a user is in (earlier for early reg people, later for normal people).

- the registration form is available even while not logged in, this should immediately redirect to auth start. You cannot register or view registrations without being logged in.
